dist: xenial
sudo: required

before_install:
  - cd
  - sudo apt-get install python-dev postgresql libpq-dev python-pip python-virtualenv git-core solr-jetty openjdk-8-jdk redis-server
  - sudo mkdir -p /usr/lib/ckan/default
  - sudo chown `whoami` /usr/lib/ckan/default
  - virtualenv --no-site-packages /usr/lib/ckan/default
  - . /usr/lib/ckan/default/bin/activate
  - pip install setuptools==36.1
  - pip install -e 'git+https://github.com/ckan/ckan.git@ckan-2.8.1#egg=ckan'
  - pip install -r /usr/lib/ckan/default/src/ckan/requirements.txt
  - deactivate 
  - . /usr/lib/ckan/default/bin/activate
  - echo 'user' | sudo -u postgres createuser -S -D -R -P ckan_default
  - sudo -u postgres createdb -O ckan_default ckan_default -E utf-8
  - sudo mkdir -p /etc/ckan/default
  - sudo chown -R `whoami` /etc/ckan/
  - paster make-config ckan /etc/ckan/default/development.ini
  - sed -i 's/sqlalchemy.url = postgresql:\/\/ckan_default:pass@localhost\/ckan_default/sqlalchemy.url = postgresql:\/\/ckan_default:user@localhost\/ckan_default/g' /etc/ckan/default/development.ini
  - sed -i 's/ckan.site_url =/ckan.site_url = http:\/\/data.laastutabloo.ee/g' /etc/ckan/default/development.ini
  - sed -i 's/#JETTY_HOST=127.0.0.1/JETTY_HOST=127.0.0.1/g' /etc/default/jetty8
  - sed -i 's/JETTY_PORT=8080/JETTY_PORT=8983/g' /etc/default/jetty8
  - sudo service jetty8 restart
  - sudo mv /etc/solr/conf/schema.xml /etc/solr/conf/schema.xml.bak
  - sudo ln -s /usr/lib/ckan/default/src/ckan/ckan/config/solr/schema.xml /etc/solr/conf/schema.xml
  - sed -i 's/#solr_url=http:\/\/127.0.0.1:8983\/solr/solr_url=http:\/\/127.0.0.1:8983\/solr/g' /etc/ckan/default/development.ini
  - ln -s /usr/lib/ckan/default/src/ckan/who.ini /etc/ckan/default/who.ini
  - cd /usr/lib/ckan/default/src/ckan
  - paster db init -c /etc/ckan/default/development.ini
  - cd /usr/lib/ckan/default/src/ckan
  - paster serve /etc/ckan/default/development.ini &
  - cd $TRAVIS_BUILD_DIR

language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt

script:
  - pytest
  - pytest tests/pytests_test.py

addons:
  ssh_known_hosts: laastutabloo.ee

before_deploy:
- openssl aes-256-cbc -K $encrypted_<...>_key -iv $encrypted_<...>_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
