sudo: required

services:
  - docker

before_install:
  - cd
  - git clone https://github.com/ckan/ckan.git
  - cd ckan 
  - git checkout tags/ckan-2.8.1
  - cd contrib/docker
  - docker-compose up -d --build
  - cd
  - cd $TRAVIS_BUILD_DIR

language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt

script:
  - pytest
  - pytest tests/pytests_test.py

addons:
  ssh_known_hosts: laastutabloo.ee

before_deploy:
- openssl aes-256-cbc -K $encrypted_<...>_key -iv $encrypted_<...>_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
